### ISSUE TITLE
Color mixer between foreground and background colors?

### ISSUE THREAD

**Issue by audreyseo** [EyeOdin/Pigment.O#11]
I was hoping to use this plugin as a replacement for Coolorus. One of my favorite features in Coolorus is the color mixing feature, which allows you to pick colors in between the foreground and background colors. I believe this is called the "blender" slider.

I'd be happy to try to take a crack at this myself, if you're taking pull requests.

**Comment by EyeOdin** [comment]
Well that would not really work.

Because you can make a mixer with the foreground and the background but once you move the mixer to any given percentage you will effectively change the foreground color because your applying the color to the canvas and then the mix will change with the mix and will apply again. the loop will maintain and you will just end up with the foreground color similar if not equal to the background color. This behavior is unmaintainable and buggy and I do not approve it.

The only way around this is to create a save state but then of the foreground and background color but then the issue persists when it is okay to update to the new foreground and background colors as you paint and mix? everyone has different workflows so there will never be a correct answer for this.

Considering that you can just use the mixer as intended that accepts any colors and mixes in any color space and will be kept in memory until you save new ones. and this just needs a click to update to your new colors to mark the new set.
