### ISSUE TITLE
consider implementing an HSLUV color selector

### ISSUE THREAD

**Issue by Gnumaru** [EyeOdin/Pigment.O#2]
Pigment.O is hands down the best color selector for krita. But even so, there is something really useful that barely any painting software (aside from Rebelle) implements, which is an hsluv color selector.

As per the site description, "HSLuv is a human-friendly alternative to HSL".

https://www.hsluv.org/

It uses the same three concepts of hsl, that is, hue, saturation and lightness, but it handles the color space differently in order to achieve actual uniform perceptual luminosity when changing hue and saturation while keeping luminosity unchanged, which is impossible with HSL.

The Rebelle painting software is the only one I have seen that has a built-in hsluv color selector, which can be seen here

https://youtu.be/tHyKrFEYtMs?t=260

It would be great if Pigment.O had an hsluv color selector. It would work the same as the hsl, but the colors shown would be calculated according to the hsluv formulas. There is already an MIT licensed python implementation for functions using those formulas.

https://github.com/hsluv/hsluv-python

**Comment by Gnumaru** [comment]
I have made a quick comparison between HSL, ARD and HSLUV. I have used hues in increments of 30 from O to 330, with saturation 100% and lightness 50%. This is the colored image.
![Screenshot (13)](https://user-images.githubusercontent.com/5783414/123076211-4993ce80-d3ef-11eb-9143-73490201a662.png)
And this is the grayscale image, viewed with soft proofing (ctrl+y).
![Screenshot (14)](https://user-images.githubusercontent.com/5783414/123076272-5b757180-d3ef-11eb-8156-36f28c0c078d.png)
the gray stripe surrounding the colors is a saturation 0%, hue 0 and ligthness 50% in hsluv (the 50% gray in hsl and ard where a little bit brighther.

It can be seen that, albeit ARD is better than HSL, it still doesnt get uniform luminosity across different hues and saturations. Hsluv has only a barely noticeable variation in lightness when viewed in grayscale.

**Comment by EyeOdin** [comment]
I am aware of CieLUV yes and it is a color space that I intend to do once I am able to.

I haven't done it yet because of constrictions from the frame work and I haven't found a way to do it properly yet. The thing is that CieLUV is XYZ based so to speak, while Pigmento only handles color spaces that are RGB based at the moment because it is what it has access too. I make HCY and YUV to try and combat this with the addiction of the Luma Lock for HSL/HSV, also I just made a ARD lock a couple of days ago that looks funny and promising, but regardless it does not have the advantage of XYZ to Yxy percision levels of black.

My problem currently is making the step from RGB to XYZ and back and then also display that color on the interface correctly.

I have done the math before for it and I had to scrap it out for the fact it producing RGB values that don't exist in their intended range as it was physically correct so all would become black where it would go out of bounds.

Also XYZ in Krita is D50 while XYZ on screens is D65 so normal formulas running around for RGB to XYZ won't work either. So the XYZ values you get in the RGB document is different from the XYZ values in the XYZ document creating a heavy discrepancy for a user.

Considering just only recently I managed to display a color correctly in other color spaces because of a new function that recently appeared in Krita. Because despite the color you have being the same in any color space if the document is RGB, CMYK, XYZ or whatever they will all display that same color diferent. So even if I had the math all right I would not be able to show it either way.

So now I am able to start working on XYZ more and try and make that happen. But this is still on the works. So after making XYZ making CieLUV happen will be easy and then I can use your conversion formulas.
