### ISSUE TITLE
Can't save color after picking color

### ISSUE THREAD

**Issue by hxse** [EyeOdin/Pigment.O#9]
![GIF 2022-3-25 3-32-07](https://user-images.githubusercontent.com/22582226/159995857-52e2dd48-0c9c-48d8-a3e4-4f19a00ce5b9.gif)

I pick a color green, but the Pigment.O can't save it, when my cursor hover Pigment.O panel, it back to color self.
I want to change the color green HSV but it doesn't work

**Comment by EyeOdin** [comment]
I had noticed it a couple of days ago but I was not to sure about what was the cause. I was even unsure if it is was a bug from my new plugin that was obstructing the system.
I will update it with the new version, that does not have that anymore. I just need to close loose ends.

**Comment by EyeOdin** [comment]
try it out now.

**Comment by hxse** [comment]
Problem solved.

**Comment by hxse** [comment]
@EyeOdin Uncheck HEX CP checkbox, the bug is disappeared.

**Comment by EyeOdin** [comment]
That is not a bug but a feature by design. CP actually stands for copy paste. This aids users using other applications to quickly use pigmento without extra clicks. if your just inside Krita you have no need to activate this and it should be turned off.

Manual:
HEX CP : Activate to copy and paste HEX codes quickly by just hovering in(paste) and out(copy) of the main widget area. Hex codes must be in the format #123456 or will be ignored.
